//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectolibreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Categoria { get; set; }
        public string Autor { get; set; }
        public int TotalInventario { get; set; }
        public string Editorial { get; set; }
        public decimal Precio { get; set; }
    }
}
