//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectolibreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaArticulo
    {
        public int ID { get; set; }
        public int IDFactura { get; set; }
        public int IDArticulo { get; set; }
    }
}
